### ISSUE TITLE
Module not functioning at all when opening a roll table

### ISSUE THREAD

**Issue by halfwalk** [DanielBoettner/better-rolltables#2]
Trying to test your branch to see if it fixed the issue, but I am unable to use the module. It is the only module enabled on a new test world. The compendiums are imported and populated, but in the roll table window, the options for Better Rolltables are nonexistent. It looks as if the module weren't enabled at all, i.e. it's just the "vanilla" rolltable dialog. (edit: Foundry 0.8.7, saveTableFix branch)

![image](https://user-images.githubusercontent.com/68490032/123320604-f9586180-d4ff-11eb-8b13-94b51677def6.png)

When opening the table, I get the following error in the console:

![image](https://user-images.githubusercontent.com/68490032/123320819-43d9de00-d500-11eb-864f-75fc522056db.png)

**Comment by DanielBoettner** [comment]
First of all thanks for testing.

The branch is outdated. I'll update this issue with a reference to a testable branch asap.

**Comment by DanielBoettner** [comment]
Please use https://github.com/DanielBoettner/better-rolltables/tree/minorImprovmentFlagsSaving for testing.
